### ISSUE TITLE
Can user update his first name with JWT token?

### ISSUE THREAD

**Issue by vladyslav2** [FusionAuth/fusionauth-javascript-client#2]
I'm not sure I got it right but I have this scenario:

1. User login using his email and password
2. Once he logged in he has some actions he can do - like update his first and last name, phone and so on

I'm not sure if frontend can do direct request to fusionapp or do I need to do it via same backend application which will handle jwt checks?
Cause I was not able to find documentation on how to update user data just with JWT

**Comment by robotdan** [comment]
The FusionAuth admin UI does not currently offer this feature for end users. 

We do not have an API to allow a User update with a JWT. Allow this has a lot of security implications - so we recommend you build this into your product instead.  This way you can provide the correct security controls and limit what the user is allowed to change. 

For example, you could take a JWT, and if valid, use the `sub` claim which is the FusionAuth `userId` to make a call to the User API (using an API key) to update whatever fields you allow in your application.
